"""empty message

Revision ID: 403c32bc50d6
Revises: fd055e39da33
Create Date: 2017-11-18 16:45:00.422683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403c32bc50d6'
down_revision = 'fd055e39da33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
